// This file is auto generated by the protocol-buffers compiler

/* eslint-disable quotes */
/* eslint-disable indent */
/* eslint-disable no-redeclare */
/* eslint-disable camelcase */

// Remember to `npm install --save protocol-buffers-encodings`
var encodings = require('protocol-buffers-encodings')
var varint = encodings.varint
var skip = encodings.skip

var Statements = exports.Statements = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

defineStatements()

function defineStatements () {
  Statements.encodingLength = encodingLength
  Statements.encode = encode
  Statements.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (defined(obj.statement)) {
      for (var i = 0; i < obj.statement.length; i++) {
        if (!defined(obj.statement[i])) continue
        var len = encodings.string.encodingLength(obj.statement[i])
        length += 1 + len
      }
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (defined(obj.statement)) {
      for (var i = 0; i < obj.statement.length; i++) {
        if (!defined(obj.statement[i])) continue
        buf[offset++] = 10
        encodings.string.encode(obj.statement[i], buf, offset)
        offset += encodings.string.encode.bytes
      }
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      statement: []
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.statement.push(encodings.string.decode(buf, offset))
        offset += encodings.string.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defined (val) {
  return val !== null && val !== undefined && (typeof val !== 'number' || !isNaN(val))
}
